WIDTH = 800
HEIGHT = 600
BOARD_WIDTH = 600
BOARD_HEIGHT = 600
PLAYER_COLORS = [None, (255, 0, 0), (0, 0, 255)]

YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

_FIRST_LAYER = .3025
_SECOND_LAYER = .6055
_THIRD_LAYER = .91

CHIP_POSITIONS = [
    [(_FIRST_LAYER, 0), (_SECOND_LAYER, 0), (_THIRD_LAYER, 0)],
    [(_FIRST_LAYER, _FIRST_LAYER), (_SECOND_LAYER, _SECOND_LAYER), (_THIRD_LAYER, _THIRD_LAYER)],
    [(0, _FIRST_LAYER), (0, _SECOND_LAYER), (0, _THIRD_LAYER)],
    [(-_FIRST_LAYER, _FIRST_LAYER), (-_SECOND_LAYER, _SECOND_LAYER), (-_THIRD_LAYER, _THIRD_LAYER)],
    [(-_FIRST_LAYER, 0), (-_SECOND_LAYER, 0), (-_THIRD_LAYER, 0)],
    [(-_FIRST_LAYER, -_FIRST_LAYER), (-_SECOND_LAYER, -_SECOND_LAYER), (-_THIRD_LAYER, -_THIRD_LAYER)],
    [(0, -_FIRST_LAYER), (0, -_SECOND_LAYER), (0, -_THIRD_LAYER)],
    [(_FIRST_LAYER, -_FIRST_LAYER), (_SECOND_LAYER, -_SECOND_LAYER), (_THIRD_LAYER, -_THIRD_LAYER)]
]